org.joget.marketplace.TimeAgoDatalistFormatter.pluginLabel=Time Ago Datalist Formatter
org.joget.marketplace.TimeAgoDatalistFormatter.pluginDesc=Return the duration against today or another date
org.joget.marketplace.TimeAgoDatalistFormatter.config=Configure Time Ago Datalist Formatter
org.joget.marketplace.TimeAgoDatalistFormatter.duration=Duration
org.joget.marketplace.TimeAgoDatalistFormatter.today=From Column Date To Today
org.joget.marketplace.TimeAgoDatalistFormatter.anotherDate=From Column Date To Another Date
org.joget.marketplace.TimeAgoDatalistFormatter.twoDates=Between Two Dates
org.joget.marketplace.TimeAgoDatalistFormatter.fromDate=From Date
org.joget.marketplace.TimeAgoDatalistFormatter.toDate=To Date
org.joget.marketplace.TimeAgoDatalistFormatter.targetDate=Target Date
org.joget.marketplace.TimeAgoDatalistFormatter.year(s)=year(s)
org.joget.marketplace.TimeAgoDatalistFormatter.month(s)=month(s)
org.joget.marketplace.TimeAgoDatalistFormatter.day(s)=day(s)
org.joget.marketplace.TimeAgoDatalistFormatter.hour(s)=hour(s)
org.joget.marketplace.TimeAgoDatalistFormatter.minute(s)=minute(s)
org.joget.marketplace.TimeAgoDatalistFormatter.tryDefaultFormatErrorMsg=[ERROR] Please try to enter in 12-hour "hh:mm a" format. Current Format(s): 
org.joget.marketplace.TimeAgoDatalistFormatter.dateOutputFormat=Date Output Format
org.joget.marketplace.TimeAgoDatalistFormatter.inclDateOutputFormat=Include Format in Output
org.joget.marketplace.TimeAgoDatalistFormatter.dateTimeFormatProcessing= Extra Date Time Format Processing
org.joget.marketplace.TimeAgoDatalistFormatter.dateTimeFormatProcessing.desc= Default format will be applied automatically, only specify if there are any extra formats. Formats should be separated by comma, e.g: yyyy-MM-dd, dd-MM-yyyy
org.joget.marketplace.TimeAgoDatalistFormatter.dateTimeFormat= Date Time Format
org.joget.marketplace.TimeAgoDatalistFormatter.dateTimeFormat.desc=Default format: "yyyy-MM-dd hh:mm a", "yyyy-MM-dd HH:mm", "yyyy-MM-dd HH:mma", "yyyy-MM-dd'T'HH:mm:ss.SSSSSS", "yyyy-MM-dd'T'HH:mm:ss", "dd-MM-yyyy hh:mm a", "dd-MM-yyyy hh:mma", "dd-MM-yyyy HH:mma", "dd-MM-yyyy HH:mm"
org.joget.marketplace.TimeAgoDatalistFormatter.dateFormat= Date Format
org.joget.marketplace.TimeAgoDatalistFormatter.dateFormat.desc=Default format: "yyyy-MM-dd", "MMMMMMMMM dd, yyyy", "dd-MM-yyyy"
org.joget.marketplace.TimeAgoDatalistFormatter.timeFormat= Time Format
org.joget.marketplace.TimeAgoDatalistFormatter.timeFormat.desc=Default format: "hh:mm a", "hh:mma", "h:mm a", "h:mma"
org.joget.marketplace.TimeAgoDatalistFormatter.justNow=just now